[project]
name = "projet-nettoyage-auto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas",
    "numpy",
    "typing>=3.10.0.0",
    "pathlib>=1.0.1",
    "tabulate>=0.10.0",
    "seaborn>=0.13.2",
    "openpyxl>=3.1.5",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

